name: MinecraftPlugin
main: server.TaahThePhoenix.MinecraftPlugin.MinecraftPlugin
version: 1.0
description: Test plugin
authors: [TaahThePhoenix]
commands:
   mcp:
      description: a test plugin
      usage: /<command>
